name: aldelar-userprofile-workflow
on:
  push:
    branches: [aldelar-dev]
    paths:
      - 'apis/userprofile/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-userprofile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: cd apis/userprofile
      - run: npm install
      - run: npm run test