name: jpoetzinger-workflow
on: 
  push:
    paths:
      - apis/user-java/**
      - .github/workflows/jpoetzinger-workflow.yml
  pull_request:
    branches:
      - main

  workflow_dispatch:

defaults:
  run:
    working-directory: 'apis/user-java'

jobs:
  user-java-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: mvn clean install
      - run: mvn test
      - name: Create issue from a failed build
        uses: nashmaniac/create-issue-action@v1.1
        if: ${{ failure() }}
        with:
          title: User-Java Build Failed
          token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
          body: Workflow failed for commit ${{ github.sha }}