name: jpoetzinger-workflow
on: 
  push:
    branches: 
      - jpoetzinger-dev
    paths:
      - apis/user-java/**
  workflow_dispatch:

defaults:
  run:
    working-directory: 'apis/user-java'

jobs:
  user-java-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: mvn clean install
      - run: mvn test