name: mpieler-poi-workflow

on:
  workflow_dispatch:
  push:
    paths:
      - apis/poi/** 
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: 'apis/poi/'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal #--filter UnitTest
    - name: Publish
      run: dotnet publish poi.sln --no-restore --no-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: POI
        path: web/**
        if-no-files-found: warn

      #create issue if build fails
