name: mpieler-poi-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'mpieler1-dev'
    paths:
      - apis/poi/** 
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: 'apis/poi/'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --filter UnitTest --no-build --verbosity normal
    - name: Publish
      run: dotnet publish poi.sln -p:PublishSingleFile=true --no-restore --no-build

      #copy
      #artifacts
      #create issue if fail
