name: trips-ci
on:
  push:
    paths:
      - apis/trips/**
      - .github/workflows/trips_ci.yml
    # paths-ignore:
    #   - '**.md'
jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/trips'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # The Go version to download (if necessary) and use.
      - name: Get Modules
        run: go get
      - name: Build
        run: go build 
      - run: go test ./tripsgo -run Unit
      - uses: nashmaniac/create-issue-action@v1.1
        if: ${{ failure() }} # only run when this job is failed.
        name: Create Issue Action
        with:
          title: Unit Test for for trips failed
          token: ${{secrets.ISSUE_TOKEN}}
          assignees: ${{github.actor}}
          labels: Challenge 3
          body: Workflow failed for commit ${{github.sha}}

