name: trips-ci
on:
  push:
    paths:
      - apis/trips/**
      - .github/workflows/trips_ci.yml
  pull_request:
    branches: 
    - main
jobs:
  build:
    name: trips_cd
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/trips'
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: openhackwsj5rp15acr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t openhackwsj5rp15acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}
          docker push openhackwsj5rp15acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}     


