name: trips-cd
on:
  push:
    branches: 
      - james-dev
    paths:
      - .github/workflows/trips_cd.yml
      - apis/trips/**
env: 
  APIPRODSTATUS: false
jobs:
  trips_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/trips'
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_URI }}/devopsoh/api-trips:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_URI }}/devopsoh/api-trips:${{ github.sha }} 
  trips_staging_deployment:    
    runs-on: ubuntu-latest
    needs: trips_build
    defaults:
      run:
        working-directory: 'apis/trips'
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhackwsj5rp15trips'
          publish-profile: ${{ secrets.TRIPS_PUBLISH_PROFILE }}
          images: '${{ secrets.REGISTRY_URI }}/devopsoh/api-trips:${{ github.sha }}'
      - run: chmod +x ../../test/healthcheck.sh
      - run: ../../test/healthcheck.sh "https://openhackwsj5rp15trips.azurewebsites.net"
      - name: "Check if the service is up then swap"
        if: ${{ env.APIPRODSTATUS == 'true' }}
        run: |
          echo "Service is up, moving to swap."
      - name: "Check if the service is down"
        if: ${{ env.APIPRODSTATUS == 'false' }}
        run: |
          echo "Service is down"
          exit 1
  trips_production_swap:
    runs-on: ubuntu-latest
    needs: trips_staging_deployment
    defaults:
      run:
        working-directory: 'test'
    steps:
      - name: "Swapping production and staging"
        run: |
          az webapp deployment slot swap --name openhackwsj5rp15trips --resource-group openhackwsj5rp15rg --slot staging  --target-slot production
          echo "production swap complete, now test "
          ./healthcheck.sh "https://openhackwsj5rp15trips.azurewebsites.net"
      - name: "Check if the prod service is up"
        if: ${{ env.APIPRODSTATUS == 'true' }}
        run: |
          echo "production service is good"
      - name: "Check if the prod service is down"
        if: ${{ env.APIPRODSTATUS == 'false' }}
        run: |
          echo "prod service is down, roll back"
          az webapp deployment slot swap --name openhackwsj5rp15trips --resource-group openhackwsj5rp15rg --slot staging  --target-slot production
          exit 1
