name: trips-ci
on:
  push:
    branches:
      - james-dev
      - 'apis/trips/**'
    # paths-ignore:
    #   - '**.md'
jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/trips'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # The Go version to download (if necessary) and use.
      # - name: Get Modules
      #   run: go get
      - name: Build
        run: go build
      - run: go test ./tripsgo -run Unit

