name: trips-cd
on:
  push:
    branches: 
      - james-dev
    paths:
      - .github/workflows/trips_cd.yml
      - apis/trips/**

jobs:
  build:
    name: trips_cd
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/trips'
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_URI }}/devopsoh/api-trips:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_URI }}/devopsoh/api-trips:${{ github.sha }}     
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhackwsj5rp15trips'
          publish-profile: ${{ secrets.TRIPS_PUBLISH_PROFILE }}
          images: '${{ secrets.REGISTRY_URI }}/devopsoh/api-trips:${{ github.sha }}'
      - run: chmod +x ../../test/healthcheck.sh
      - run: ../../test/healthcheck.sh "https://openhackwsj5rp15trips.azurewebsites.net"
      # - run: az webapp traffic-routing set --distribution staging=50 --name openhackwsj5rp15trips --resource-group openhackwsj5rp15rg
