name: userprofile-ci
on:
  push:
    paths:
      - apis/userprofile/**
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: 'apis/userprofile/'

jobs:
  userprofile-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm run test
      - uses: nashmaniac/create-issue-action@v1.1
        name: Create Issue Action
        if: ${{ failure() }}
        with:
          title: userprofile Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: userprofile-build-failure
          body: Workflow failed for commit ${{github.sha}}